ALTER TABLE "VibixSyncJob" ADD COLUMN IF NOT EXISTS "lastFailedType" TEXT;
ALTER TABLE "VibixSyncJob" ADD COLUMN IF NOT EXISTS "lastFailedPage" INTEGER;
ALTER TABLE "VibixSyncJob" ADD COLUMN IF NOT EXISTS "lastFailedAt" TIMESTAMP(3);
ALTER TABLE "VibixSyncJob" ADD COLUMN IF NOT EXISTS "lastSkippedType" TEXT;
ALTER TABLE "VibixSyncJob" ADD COLUMN IF NOT EXISTS "lastSkippedPage" INTEGER;
ALTER TABLE "VibixSyncJob" ADD COLUMN IF NOT EXISTS "skippedPagesJson" TEXT;
ALTER TABLE "VibixSyncJob" ADD COLUMN IF NOT EXISTS "safeResumeNote" TEXT;
